### ISSUE TITLE
NodeBots AU swag

### ISSUE THREAD

**Issue by ajfisher** [nodebotsau/nbdau#23]
Okay - does anyone know of a place where we might be able to get some "nice" stickers created that are the AU versions of the nb logo? Some of you might have seen some of the new nb stickers I had at CampJS which came from @rockbot - they are pretty good so would be good to be able to hand out at our days.

Likewise, if anyone knows a place we can get t-shirts made (or indicative prices for what might be involved with that) then again, would be good to explore as an option.

**Comment by gerendasi** [comment]
Speaking of cool stickers, check out Tabtag: http://www.tabtag.com
I imagine there'd be plenty of Mac users interested in these.
