### ISSUE TITLE
Machine Learning breakout session at NBDMelb

### ISSUE THREAD

**Issue by hadimichael** [nodebotsau/nbdau#26]
Hi all, is anyone interested in getting involved in a machine learning / AI focused breakout session at NBD? Do people think this is something that would be appropriate for the day?

I'm keen to see a stronger focus on the software side of robotics. I'm thinking we can use ML to learn something from physical sensors and then have the bot react accordingly. Nothing too crazy. The core objective would be to get people thinking about connecting the software to the hardware.

I'm looking at libraries like:
Neural network learning: https://github.com/harthur/brain
Natural language detection: https://github.com/NaturalNode/natural
++ all the computer vision stuff that we could integrate...

**Comment by geekscape** [comment]
Looks like we may finally make a start on this ... this year !
