### ISSUE TITLE
Projects, workshops - Melbs

### ISSUE THREAD

**Issue by ajfisher** [nodebotsau/nbdau#33]
Any particular projects / workshops interest ideas that anyone wants to see.

I know @hadimichael was considering some ML stuff and @geekscape was considering some Pixy and MeshThing things?

We've got ARDX kits available as well as SimpleBot kits so those are definitely good to go.

I've got a couple of bluetooth modules and I also have a couple of WiFi-Serial modules too so potentially can go wireless (before going "full mesh"). 

As we've got a couple of weeks, I'm assuming we can create materials for anything else if we have parts to hand.  

Any suggestions?

Cheers
Andrew

**Comment by sidorares** [comment]
@andykitchen is great in all things AI/ML ( and demoing this stuff ). Wonder if we could get him on board

**Comment by ajfisher** [comment]
I'll ask now...

**Comment by garrows** [comment]
Sorry for closing. I did a bulk close of anything without comment for 2 years.

**Comment by geekscape** [comment]
Yes, @andykitchen is great !  There has been some stealth A.I NN hacking going on in the background ... with an aim to bring "worked examples" to the next NodeBots Days (and also the next BuzzConf) events.

**Comment by ajfisher** [comment]
Closing this out now in prep for NBD 2018
