### ISSUE TITLE
Sydney 2016 Event Logistics - 30/07

### ISSUE THREAD

**Issue by DamonOehlman** [nodebotsau/nbdau#48]
Hey folks,

Rather than attempt to capture all the things we need to make the event go in the gitter chat I thought I'd create a high level issue here:

- [x] Venue
- [x] Food / Drinks
- [x] Hardware
- [x] Mentors (had some good expressions of interest, just need to firm these up)

Given the short time frame until this event, I'm keen to focus on items 1 and 2 and potentially ease back on the tickets where people actually walk away from kit with the event.  This is something for discussion though, as if it's something that anyone has some great ideas for then we should definitely consider it.

Cheers,
Damon.

**Comment by ajfisher** [comment]
Excellent idea. I think we'll have some spare equipment in all the ordering
I've just done to potentially have some kits if you need them.

Focus on the top 2 and if you can leverage what we're doing then is just
gravy I reckon.

**Comment by catherine-jones** [comment]
So we can run the event at my office in Surry Hills that's not a problem. I can also look into some food options.

**Comment by JohnAllsopp** [comment]
The event falls on the weekend between our Sydney and Melbourne Code conferences - so hopefully we can promote it to our audiences, but glad it can be hosted at DTO as we'll likely be a bit hectic in that period.

Very happy to provide thoughts and support around logistics.

Should we loop in Justin Mclean from IOTSydney? They've got a great community around this space and he'd be a gretcontrobutior IMO.

**Comment by DamonOehlman** [comment]
@JohnAllsopp cool - Yeah I was trying to locate Justin on github or email but couldn't find anything.  He's participated in one a couple of years ago and was a great asset then so would love him to be involved again if he is available :)

So should we all agree that the 30/07 is the best date for Sydney (feel free to respond with reactions), for the following reasons:

1. Falls between Web Directions Code Sydney and Melbourne
2. Gives us a little more breathing room to pull it all together
3. Any excess kits from Melbourne / Brisbane could make their way down to Sydney for those interested

If this is good for everyone / most folks then I'll update the title on the issue to reflect our commitment to that date.

**Comment by JohnAllsopp** [comment]
Shall I follow him up?

On 14 June 2016 at 09:27, Damon Oehlman <notifications@github.com> wrote:

> @JohnAllsopp <https://github.com/JohnAllsopp> cool - Yeah I was trying to
> locate Justin on github or email but couldn't find anything. He's
> participated in one a couple of years ago and was a great asset then so
> would love him to be involved again if he is available :)
>
> So should we all agree that the 30/07 is the best date for Sydney (feel
> free to respond with reactions), for the following reasons:
>
>    1. Falls between Web Directions Code Sydney and Melbourne
>    2. Gives us a little more breathing room to pull it all together
>    3. Any excess kits from Melbourne / Brisbane could make their way down
>    to Sydney for those interested
>
> If this is good for everyone / most folks then I'll update the title on
> the issue to reflect our commitment to that date.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/nodebotsau/nbdau/issues/48#issuecomment-225738009>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAKvHR-98RoXS5cc5hMf-AQAH-qYjgEaks5qLedagaJpZM4I0Cte>
> .
>



-- 
john allsopp
@johnallsopp
+61 0405 149 597

**Comment by DamonOehlman** [comment]
@JohnAllsopp yes please :)

**Comment by JohnAllsopp** [comment]
OK, so Justin is justinmclean

Also, Patrick Catanzariti?

**Comment by DamonOehlman** [comment]
Sweet, /cc @justinmclean (must have been a spelling issue on my part when searching).

Unfortunately @patcat is overseas at that time and is (sadly) unable to participate.

**Comment by JohnAllsopp** [comment]
shame about patcat

j

On 14 June 2016 at 10:45, Damon Oehlman <notifications@github.com> wrote:

> Sweet, /cc @justinmclean <https://github.com/justinmclean> (must have
> been a spelling issue on my part when searching).
>
> Unfortunately @patcat <https://github.com/patcat> is overseas at that
> time and is (sadly) unable to participate.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/nodebotsau/nbdau/issues/48#issuecomment-225750565>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAKvHR4CwwKkQvFzO2-eawhLvDuFkFMZks5qLfnFgaJpZM4I0Cte>
> .
>



-- 
john allsopp
@johnallsopp
+61 0405 149 597

**Comment by DamonOehlman** [comment]
@catherine-jones Any info you can provide on the number of people that the venue can hold?  Given you are in Surry Hills maybe I should pop over for a visit sometime to get a feel for it.  Running nodebots generally needs some allocation of desk space for people to hack on things and then if they have driving type projects they are working on (which we may not be attempting to do this Sydney event) then some random floor space also.

Thanks again for offering up a venue, it makes a big difference to being able to host an event :)

**Comment by catherine-jones** [comment]
@DamonOehlman So the floor we are currently on can accomodate a maximum of 60 people.  We are expected to be getting another floor at the end of this month but these things normally get delayed so if we stick to the one floor I think it will be a lot easier. If you want to come check out the office that would be great. I am interstate next week but I will be back in the office on the 28th if you want to stop by.

**Comment by DamonOehlman** [comment]
@JohnAllsopp I know you are probably really busy mate, but just wondering if you might be able to coordinate with @catherine-jones for a trip out to the DTO office to see how well the space will work for Nodebots?  I head away for a fortnight starting tomorrow and @catherine-jones and I haven't been able to sync up today, so would really appreciate it if you could spare the time.

**Comment by JohnAllsopp** [comment]
Happily @DamonOehlman 

@catherine-jones I'm round today - any time suit?

j

**Comment by DamonOehlman** [comment]
Sorry @JohnAllsopp - I forgot to clarify that @catherine-jones is out of the office today which is why we couldn't manage to catch up.

**Comment by JohnAllsopp** [comment]
gotcha - @catherine-jones just let me know when might suit, I'm in most days, everyday this week

**Comment by catherine-jones** [comment]
What about between 10 and 1 tomorrow @JohnAllsopp?

**Comment by JohnAllsopp** [comment]
sorry @catherine-jones does 1230 work? what floor you folks on?

**Comment by web-goddess** [comment]
Hey all - Thanks for looping me in, Damon. Let me know what I can do to help out. I can definitely promote via the usual Girl Geeks channels. I can also put in a few hours at the event itself. (May be tricky as it's my husband's birthday!)

**Comment by catherine-jones** [comment]
@johnallsop sorry just saw your message at lunch now does 1.30 work?

**Comment by JohnAllsopp** [comment]
sure - see you up there around then?

j

On 28 June 2016 at 12:49, Catherine <notifications@github.com> wrote:

> @johnallsop sorry just saw your message at lunch now does 1.30 work?
>
> Sent from my iPhone
>
> > On 28 Jun 2016, at 12:01 PM, John Allsopp <notifications@github.com>
> wrote:
> >
> > sorry @catherine-jones does 1230 work? what floor you folks on?
>
> >
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub, or mute the thread.
> >
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/nodebotsau/nbdau/issues/48#issuecomment-228934252>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAKvHfTz8oIcPLuA7Mv31bNGSistZn2kks5qQIvIgaJpZM4I0Cte>
> .
>



-- 
john allsopp
@johnallsopp
+61 0405 149 597

**Comment by catherine-jones** [comment]
@johnallsop 241 commonwealth st level 2. You will need to give me a call 0404843789 so I can let you up

**Comment by JohnAllsopp** [comment]
just shot you an email @catherine-jones

**Comment by JohnAllsopp** [comment]
Just dropped by to see the DTO premises - I think it will work really well. A good sized screen for any presentations, and there'll be tables spread across a reasonable sized area. In all, will be a great space.

The floor has a maximum number of 60, so we'll have to think about how to make RSVPs work.

Next steps?

**Comment by catherine-jones** [comment]
Hi Team,

So now that we are all set for the venue. I was just wondering if anyone had suggestions/ideas on everything else such as ticketing and kits? I think we should defiantly order kits ASAP so they arrive in time

**Comment by jtj02** [comment]
I should be able to bring around 10 ed1 boards to loan out for the day.

Regards,
John Judge

**Comment by DamonOehlman** [comment]
Hey folks - back from holiday yesterday and starting to get a handle on things back at home.  I'll look at setting up a ticketing page shortly.  Everyone else seems to be using eventbrite but we've had a good relationship with ti.to through CampJS so I'll probably go with that for the Sydney event.

From a ticketing tiers perspective, I think we should just go with a flat rate price rather than the more complicated pricing (probably just a $20 ticket, with perhaps a $10 student ticket option available).  I'll see if I can source some gear that we can use on the day - possibly encouraging people to work together to keep the total number of boards that we might need in Sydney to a sensible quantity.

I came across this online retailer tonight that seems pretty reasonable price wise so might get in touch with them:

http://www.auselectronicsdirect.com.au/

With regards to covering the cost of hardware, that could probably be done with some left over funds from the most recent CampJS before it all gets transferred into the hopefully soon to be created JS Australia org (/cc @twalve). I'm hoping that JS Australia can help out with some of the financial stuff with Nodebots as well so this doesn't have to be taken care of by individuals as I assume it is now (this has certainly been the case for CampJS).

**Comment by DamonOehlman** [comment]
OK - I've put in an order with that site so hopefully that all works out nicely.  I've reconsidered only having the one price point and I think we should have:

1. 30 x Regular Ticket - $20
2. 30 x Experimenter Ticket - $40 (Includes Arduino Nano Board but no additional hardware)

A __STUDENT__ discount code will be available for both tickets which will apply a $10 discount to both tickets.

In terms of hardware, the aus electronics site lists a list of self contained modules and I've purchased variety of those for people to experiment with on the day and purchased a swag load of jumper lead in various configurations (plug - plug, plug - socket, even a few socket - socket).  All being well that will be delivered in the next couple of days and I'll have a handle on whether we do need any backup supplies from interstate.

**Comment by DamonOehlman** [comment]
Just letting folks know that the hardware arrived today and it's looks like I've got a good selection.  Need to inventory it all to make sure it is all there and run a few cursory checks but we are looking good :)

I'll put a ticket site up in ti.to and let people know here.  There will additionally be a __MENTOR2016__ discount code that will take $20 off the price - essentially making the regular ticket free.  This is of course assuming you are coming along to help folks out ;)

**Comment by DamonOehlman** [comment]
Ticket site live - if mentors could register that would be great.  I've made 60 tickets total available based on the advice of @JohnAllsopp and @catherine-jones but we could drop that to 50 for the time being to give us a little headroom if we need it.

**Comment by twalve** [comment]
I'm happy to wrangle many folks if you need more mentors! And attendees of course
I'll definitely be there 💃 

I'll make a slide for next Wednesday night's SydJS and the Wednesday after's SydJS/SydCSS combo event

**Comment by twalve** [comment]
<img width="1199" alt="screenshot 2016-07-13 22 13 06" src="https://cloud.githubusercontent.com/assets/89387/16802972/e4906f76-4946-11e6-919e-b0418160c9fd.png">

**Comment by twalve** [comment]
If that doesn't fill all 50 slots I don't know what will! 😄

**Comment by justinmclean** [comment]
Hi,

I’ll sign up as a mentor for the day I’ll also email Sydney mailing list (1300+ people) in a day or two so hopefully you’ll get a few sign up from that.

I may be able to wrangle a few mentors as well how many do we need?

Other than my usual kit (soldering iron and kit and few random bit and pieces) is there anything else you expect mentors to bring along?

Thanks,
Justin

**Comment by lyntco** [comment]
I'll pass it on to the other I know people happy to mentor - what's the link?

**Comment by DamonOehlman** [comment]
Oh yeah, a link to the ticket page... I forgot to include that:

https://ti.to/nbdau/nodebots-syd-2016

Any typos LMK and I'll update it :)

**Comment by DamonOehlman** [comment]
@justinmclean @lyntco Thanks.  In terms of mentor numbers, it's always a bit hard to tell.  If we assume that we have 60 people though, and 50 people have zero experience with some aspect of nodebots (either the software or the electronics), then having 10 mentors would probably be ideal.  It would also be the most I expect we've had at a Nodebots event (though I didn't make it along last year, so I don't know).

Justin - with regards on what to bring.  Bringing along the soldering iron would be great, and if there are any electronics components that you would normally be using to introduce people to when they get started that would be great also (I'm happy to reimburse you for cost of replacement, or whatever you purchase for the day).

We don't have kits like previous years, but rather I've opted to purchase a variety of [these self-contained sensors](http://www.auselectronicsdirect.com.au/arduino/arduino-sensors/) for people to experiment with on the day.  This should be able to give folks a similar experience to what they get with the ED1 boards that @jtj02 will be bringing along.  That does, however, leave a gap around actually understanding some electronics basics which I'm sure some folks will be interested in.  I know yourself, John Judge and Callum Smits would be able to help with.

**Comment by DamonOehlman** [comment]
Also, a nice writeup from @cheshrkat on the ED1 from the first time we ran the event in SYD:

http://weblog.200ok.com.au/2013/07/nodebots-sydney-2013-and-nicta-ed1.html

**Comment by cheshrkat** [comment]
Heh, too kind.

**Comment by patcat** [comment]
Seriously disappointed that I'll be missing this!!! I'm keen to try to at least spread the word about it via my Dev Diner newsletter and social medias — what is the best link/links to share with people to encourage them to come along?

**Comment by DamonOehlman** [comment]
@patcat I guess probably the nodebotsau.io page as I'd hate for them to hit the ticket page and just find there are no tickets left.  That said, the ticket page does have the site URL up there fairly prominently so I think it's probably your call mate :)

Tickets URL: https://ti.to/nbdau/nodebots-syd-2016

**Comment by DamonOehlman** [comment]
Not long to go now folks.  Of the 50 (I've left 10 up our sleeve) tickets available for sale, all but 9 are sold.  In terms of remaining todos before Saturday, there is:

- Organise some lunch catering. I've made contact with Taste Baguette who are just around the corner from the event location.  We very occasionally have these at Canva and I think they are excellent :)

- Provide some clarification on the website as per #49 regarding the date, though I guess it might be less of an issue now.  Still worth doing though.

- Think about the logistics of getting people into DTO. I'm assuming there is some kind of pass security, and if so we'll need a volunteer to let people into the building and put their mobile number up somewhere so late comers can get into the building.

- Register if you are coming along to the event and haven't already.  __NOTE:__ If you are thinking of dropping in for a couple of hours and helping our with mentoring, that's pretty much what the additional ticket headroom is for.  If you are going to be around at lunchtime though please let me know and I'll include you in the what would you like to eat for lunch mail out :)

Stuff done:

- Sold tickets
- Received all the gear
- [Wrote some examples](https://github.com/DamonOehlman/nbd2016-syd) for the gear I've received and test that the specific modules are working.  Some of the items (not yet listed) proved to be not yet supported into nodebots land, so I might include them in a stretch goals section if anyone does want to have a play.

**Comment by DamonOehlman** [comment]
@catherine-jones Just wondering if there are any other folks from DTO coming along on the day?  If not, would you be happy to be the contact person for people coming in late?  Again, I'm assuming that there are some security swipe access points and if there aren't then LMK :)

**Comment by catherine-jones** [comment]
@DamonOehlman I think it's just going to be me possibly one more but not counting on it.  I am happy to be the contact person, people will need an access pass to get in and out of the level. I will try and get some spares. Let me know if you need anything else

**Comment by callumsmits** [comment]
@DamonOehlman I'm registered for Saturday and will be around most of the day including lunch :).    I was wondering if there was any point bringing some other kit along - a few raspberry pis? I have also have some ESP8266's ([D1 Mini's](http://www.wemos.cc/)) but when I put espruino on them a simple digitalWrite seemed to hang them so not sure if they're so useful.

**Comment by justinmclean** [comment]
Hi,

I’ll should be about all day (including lunch) as well.

Thanks,
Justin

**Comment by DamonOehlman** [comment]
Thanks folks - apologies I missed all the replies due to poor email management :(

@catherine-jones Sounds great - thanks.

@callumsmits Absolutely - feel free to bring whatever you want (also @justinmclean), the main aim of nodebots is to open a world of possibilities to people they hadn't considered, and also give more experienced folks a day to get together with others and just hack on stuff :)

Also, I've investigated a few options with regards to catering, and while I'd love to do something more fancy on the day, I think the simplest option that caters for a variety of dietary requirements will be mainstream pizza delivery.  I'm going to send out a survey tonight asking people for their favourite people and whether they have any dietary requirements (gluten free, cheese free).  I'll include the ability to specify a custom pizza option too for people with more specific dietary requirements, i.e. vegan.

I'll also look at getting something for afternoon tea in case people are peckish in the afternoon.

**Comment by johnk-** [comment]
Hi. It would be a good idea to send out a reminder email to the attendees with times, location, what to bring etc. Thanks again for organising -John

**Comment by DamonOehlman** [comment]
@johnk- Yep - that's on the list of things TODO tonight :)

**Comment by jtj02** [comment]
@DamonOehlman I can confirm that I have 10 ed1 boards to bring on Saturday
