### ISSUE TITLE
Confusion with dates

### ISSUE THREAD

**Issue by justinmclean** [nodebotsau/nbdau#49]
Can someone fix http://nodebotsau.io as it states it's on the 23rd not the 30th

**Comment by justinmclean** [comment]
Also front page has "July 25th"

**Comment by ajfisher** [comment]
So there will be a little bit of confusion here as Melbs and Bris ARE
actually the 23rd not the 30th. I'll see if I can make some mods but if
someone from the Sydney crew wants to jump in and edit and raise a PR that
would be fantastic at this point.
