### ISSUE TITLE
Unable to install Interchange

### ISSUE THREAD

**Issue by tcreuro** [nodebotsau/nbdau#55]
`npm install -g nodebots-interchange` 

Issue:

Failed at the serialport@4.0.7 install script

**Comment by ajfisher** [comment]
I think I know what this is - what version of node are you running?

**Comment by ajfisher** [comment]
@tcreuro for the moment there's a dependency problem with serial port on node 10. I'll raise a PR with avrgirl to get that resolved though so if you can switch back to node 8 (eg using nvm) then you can install fine.

**Comment by tcreuro** [comment]
OK and thank you. I will downgrade from 10.6.0 to 8.

**Comment by tcreuro** [comment]
Here is an article on how to downgrade for node 10 to 8 using brew.

https://medium.com/@katopz/how-to-install-specific-nodejs-version-c6e1cec8aa11

**Comment by ajfisher** [comment]
Also note that nvm is your friend here. I would highly recommend the use of
NVM to manage different node versions rather than a single install

**Comment by ajfisher** [comment]
This should be fixed now as well as a result of this and related changes

https://github.com/johnny-five-io/nodebots-interchange/commit/3cc00ddd5be9583a9992668d99dd1d1805b585f9

NPM registry has been updated with newer version also.
